### PR TITLE
Ldap stubs update

### PR DESCRIPTION
**Pull request by brainfoolong**
Added and updated all stuff according to https://www.php.net/manual/en/ref.ldap.php
This stub was missing many new functions and constants.

### CODE REVIEW

**Comment by brainfoolong** [comment]
Test fail because of stubs map check. I've updated as suggested in the readme.
One thing i see is that 2 same functions with name `strstr` exists. 

One in https://github.com/JetBrains/phpstorm-stubs/blob/fd6517b8916331d78cb4fa31bd19a787a693d1da/standard/standard_1.php#L661 and one in https://github.com/JetBrains/phpstorm-stubs/blob/fd6517b8916331d78cb4fa31bd19a787a693d1da/standard/_standard_manual.php#L8

Maybe this cause some inconsistencies.

**Comment by MaXal** [comment]
Sorry about `strtr`. I've moved `strtr' to 'standard/standard_1.php' to avoid the map flakiness. Please revert: `strtr' => 'standard/standard_1.php',` change in the `PhpStormStubsMap`.

**Comment by brainfoolong** [comment]
Ok. Stubs map check now successfull but the job still fails.
Error still come from strtr

https://travis-ci.org/JetBrains/phpstorm-stubs/builds/571371998#L979

**Comment by brainfoolong** [comment]
@bzixilu Have i done something wrong or was this close/reponen a misclick?

**Comment by bzixilu** [comment]
@brainfoolong Everything is fine, no worries :) Close/reopen actions were required to rerun Travis, sorry for the inconvenience.

**Comment by brainfoolong** [comment]
Ah, i see. It's passed now :)

**Comment by bzixilu** [comment]
Thank you for your contribution!

P.S. We have added new tests on ldap stubs after your pull-request, see ba392f347ad4af01f1cef9f0fd501c50bd59438b for more details.

Also, a few additional minor fixes were done to make the new tests green. See dc145f6f6aed6068059fddb09059a02b239f0813

**Comment by brainfoolong** [comment]
Great. Thank you.

**Pull request merged**
