### PR TITLE
couchbase: update to 3.1.0

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by MaXal** [comment]
Couchbase SDK was introduced on 10 January 2020 and it completely changes the available classes. I believe it makes sense to preserve SDK version 2 and introduce SDK version 3 in addition to not break older projects. 

Please also fix the test failure:
```
1) StubTests\StubsPhpDocTest::testMethodsPHPDocs with data set "method Couchbase\DocIdSearchQuery::__construct" ('__construct', StubTests\Model\PHPMethod Object (...))
Element method __construct has invalid tag: @ignore
Failed asserting that an array contains 'ignore'.
```

We don't support `@ignore` tag so please remove it.

**Comment by avsej** [comment]
@MaXal, I can preserve the old stubs too, but what is the process for multiple versions of the extensions?

**Comment by MaXal** [comment]
You may add your new stubs into `couchbase_v3/couchbase.php`. This way it will be possible to enable/disable separate versions. There is, unfortunately, no way to version stubs per library version.

**Comment by avsej** [comment]
@MaXal thank you. I've updated PR, now it renamed the old directory to `couchbase_v2` and `couchbase` has stubs for current version of the extension

**Comment by voskobovich** [comment]
@MaXal, please tell me what else is needed to accept this PR?

**Comment by MaXal** [comment]
We've updated our test infrastructure to support duplicated classes. So the merge should come soon:)

**Comment by isfedorov** [comment]
Docker failed to download image. `Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/99/9948f4e264c703b9fb9fd8db8b11146cb8eb17f113f4f427d5bf3c647ace3e75/data?verify=1614771306-%2Be3NZ7ocVjRLu9ia90mvTzVdovI%3D: net/http: TLS handshake timeout` Reopening to try one more time

**Comment by isfedorov** [comment]
@avsej could you please rebase your branch on upstream/master, execute `docker-compose -f docker-compose.yml run php /usr/local/bin/php /opt/project/phpstorm-stubs/generate-stub-map` and commit the resulting `PhpStormStubsMap.php`?

**Comment by isfedorov** [comment]
fixed in #1078

**Pull request closed without merging**
