### PR TITLE
Add ffi extension support

### PR DESCRIPTION
**Pull request by SerafimArts**
Adds autocomplete and a brief description of the FFI extension from the current php-src master (PHP 8.0.0-dev) branch.

Relation link: https://github.com/dstogov/php-ffi

### CODE REVIEW

**Comment by SerafimArts** [comment]
Hmmm... I do not understand the reason why tests do not pass. Can anyone explain the reason?

**Comment by MaXal** [comment]
@SerafimArts Sorry, it was our fault. I've restarted the build.

**Comment by andrey-sokolov** [comment]
Perhaps, it worth to wait till PHP 8.0 released in case the extension-API will be completely changed. For now, it should be enough to add this stub locally.

**Comment by SerafimArts** [comment]
Then it will be no longer version 0.1.0 of this extension. Approximately as in the case of `ext-ev`, when API was completely rewritten during the transition from 1.0 to 2.0 (if I do not confuse)

**Pull request merged**
