### PR TITLE
Add openssl_get_cert_locations

### PR DESCRIPTION
**Pull request by kelunik**
Available since PHP 5.6

### CODE REVIEW

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by kelunik** [comment]
Wow, you make it really complicated to contribute. Why do you need my address?

**Comment by neuro159** [comment]
Legal requirements (

**Comment by kelunik** [comment]
Ok, closing this then.

**Comment by samayo** [comment]
I'm surprised he didn't ask you for your blood sample

**Comment by neuro159** [comment]
We're trying to actually fix the process but now this LA is a requirement (

**Comment by mckaygerhard** [comment]
jajaJA stupid licenses... get free software rules!

**Pull request closed without merging**
