### PR TITLE
Resolve WI-28823 Add APCu stubs

### PR DESCRIPTION
**Pull request by kkopachev**
see https://youtrack.jetbrains.com/issue/WI-28823

### CODE REVIEW

**Comment by neuro159** [comment]
scan and email to contribute@jetbrains.com!

**Comment by klikh** [comment]
We've received the CLA. Thanks.

**Comment by xjewer** [comment]
so that, when will pr have merged?

**Comment by BenMorel** [comment]
+1, need this as well. Please merge!

**Comment by stof** [comment]
@klikh is there some plans to merge this for the next PhpStorm version ?

**Pull request merged**
