### PR TITLE
Adding stub for https://github.com/kjdev/php-ext-snappy.

### PR DESCRIPTION
**Pull request by schodemeiss**
Added stubs for the Snappy Compression extension found here: https://github.com/kjdev/php-ext-snappy.

### CODE REVIEW

**Comment by DmitryTronin** [comment]
Do you have any installations or usage stats for this extension?

**Comment by schodemeiss** [comment]
> Do you have any installations or usage stats for this extension?

I do not; only anecdotal evidence of a handful of companies using it in production. The extension I reference in the docs does seem to be the most current and the one I've seen most used in the field.

**Comment by schodemeiss** [comment]
Ah, I didn't notice we had to update the map. I shall do that, make another commit and go again :-).

**Comment by DmitryTronin** [comment]
Just one more thing, as the test error advises: _Stubs directories provider doesn't contain 'snappy'. Please add 'snappy' to 'PhpCoreStubsProvider::StubDirectoryMap'_

**Pull request merged**
