### PR TITLE
WI-54952: fix rdkafka stubs, generator

### PR DESCRIPTION
**Pull request by nick-zh**
Moved functions where needed, to reflect the the state of the extension:
https://github.com/arnaud-lb/php-rdkafka/blob/master/rdkafka.c#L726-L743

As per the below discussion, also adjusted the stub generator to recurse into sub-folders, since this caused some issues without it

### CODE REVIEW

**Comment by nick-zh** [comment]
Is it possible that nested directories are not recognized?
I updated `PhpStormStubsMap.php` as per readme, but the result does not seem to differ (which in my case makes sense probably), but i was only able to find the files in the root of rdkafka

**Comment by ondrejmirtes** [comment]
Well you haven't added or removed any files so I don't see why `PhpStormStubsMap.php` should change.

**Comment by ondrejmirtes** [comment]
But you're right that classes from RdKafka are missing in the map.

**Comment by nick-zh** [comment]
So i moved all the classes to the root folder, so they are present in the stubs map, i hope that is ok

**Comment by ondrejmirtes** [comment]
Might be worth fixing the generator script instead, shouldn't be hard. Maybe it finds other namespaces with the same problem.

**Comment by nick-zh** [comment]
Agreed, i fixed it accordingly :v:

**Comment by ondrejmirtes** [comment]
Awesome, more stubs available :)

**Comment by nick-zh** [comment]
@slapoguzov @andrey-sokolov please let me know if any more changes / adjustments are needed :v:

**Comment by slapoguzov** [comment]
thank you!

**Pull request merged**
