### PR TITLE
mysql_xdevapi_8_0_11

### PR DESCRIPTION
**Pull request by mhgs**
Updated mysql_xdevapi stub based on official documentation (version 8.0.11)

### CODE REVIEW

**Comment by mhgs** [comment]
@bzixilu I see the build has failed, however I cannot see why? If there is a issue with the changes I would like to fix it of course. Can you point me in the right direction?

**Comment by soulshockers** [comment]
> @bzixilu I see the build has failed, however I cannot see why? If there is a issue with the changes I would like to fix it of course. Can you point me in the right direction?

The commited stub map is not up to date. Please regenerate it using ./generate-stub-map

**Comment by mhgs** [comment]
@soulshockers Thanks, that fixed it.

**Comment by bzixilu** [comment]
The tests passed successfully against https://github.com/nexilo/xdevapi-php/blob/master/docker/php/Dockerfile

**Comment by bzixilu** [comment]
Thank you for the contribution!

**Pull request merged**
