### PR TITLE
add method target to LanguageLevelTypeAware

### PR DESCRIPTION
**Pull request by isfedorov**

### CODE REVIEW

**Comment by wbars** [comment]
@isfedorov Intrinsic support in PS for this attribute should be updated to support this, please create YT issue with real-life scenarios that will be solved by this.

**Comment by isfedorov** [comment]
Added https://youtrack.jetbrains.com/issue/WI-58641

**Comment by wbars** [comment]
I can't give any estimates on the issue, let's reopen PR once issue will be resolved.

**Comment by wbars** [comment]
https://youtrack.jetbrains.com/issue/WI-58641 is landed into master

**Review by wbars — APPROVED** [review]

**Pull request merged**
