### PR TITLE
Corrected signature and PhpDoc for link() function

### PR DESCRIPTION
**Pull request by MightyPork**
The signature and comment were incorrect. 

Updated according to http://php.net/manual/en/function.link.php

### CODE REVIEW

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by MightyPork** [comment]
I don't have a printer. 

Copy the patch and add it yourself, if you care so much about some stupid agreement.

**Comment by neuro159** [comment]
I don't care, I'm legally bound to.
Posting patches while violating CONTRIBUTING.md to any project just makes author's life more complicated. Fortunately your change is trivial, and I can just get this info from public docs. In complex changes one may need to prove clean room implementation. 

Please just open an issue describing what's wrong in project's issue tracker if you can't sign the CLA.

**Comment by MightyPork** [comment]
The issue is open here: [WI-28829](https://youtrack.jetbrains.com/issue/WI-28829).

I have been told by Maxim Kolmakov that I'm welcome to contribute. Doesn't look like it.

Enjoy your bug.

**Pull request closed without merging**
