### PR TITLE
Fixed header signature

### PR DESCRIPTION
**Pull request by boekkooi**
Related to https://youtrack.jetbrains.com/issue/WI-19134

### CODE REVIEW

**Comment by neuro159** [comment]
Please avoid any unnecessary changes i.e. spacing. These files are NOT for human consumption.

**Comment by boekkooi** [comment]
Thanks for the comment and please don't close PR's that can be fixed! just command I will update

**Comment by boekkooi** [comment]
Removed auto trimmed lines

**Comment by neuro159** [comment]
This goes to ALL requests. auto trims, <br>->newline and similar.

**Comment by boekkooi** [comment]
@neuro159 It should be fixed in all of them now

**Comment by neuro159** [comment]
Thanks! We'll try to keep this alive and merge stuff ASAP, but we still need to refine the process. Amended the guidelines...

**Comment by thaJeztah** [comment]
@neuro159 https://github.com/JetBrains/phpstorm-stubs/issues/3 ?

**Pull request merged**
