### PR TITLE
Create stub for libsodium

### PR DESCRIPTION
**Pull request by paragonie-scott**
https://github.com/jedisct1/libsodium-php/issues/77

As noted in the original version in Halite, I'm releasing this under WTFPL/CC0 but I will sign a contributor agreement too.

### CODE REVIEW

**Comment by garethnic** [comment]
This would be pretty awesome.

**Comment by moderndeveloperllc** [comment]
@neuro159 Any particular reason this hasn't been merged? Thanks.

**Comment by moderndeveloperllc** [comment]
@paragonie-scott It looks like this doesn't include the latest constants like:
```
crypto_pwhash_ALG_DEFAULT
crypto_pwhash_SALTBYTES
crypto_pwhash_STRBYTES
crypto_pwhash_STRPREFIX
crypto_pwhash_OPSLIMIT_INTERACTIVE
crypto_pwhash_MEMLIMIT_INTERACTIVE
crypto_pwhash_OPSLIMIT_MODERATE
crypto_pwhash_MEMLIMIT_MODERATE
crypto_pwhash_OPSLIMIT_SENSITIVE
crypto_pwhash_MEMLIMIT_SENSITIVE
```

**Comment by neuro159** [comment]
can you please move the stub into its separate folder (==module name)?
we're in the midst of the cleanup to simplify control over modules
(UI allowing per-project switching is also added)

**Comment by neuro159** [comment]
+fixed naming / location

**Pull request merged**
