### PR TITLE
Added aggregateCursor to mongo stubs

### PR DESCRIPTION
**Pull request by hver**

### CODE REVIEW

**Comment by neuro159** [comment]
Please follow https://github.com/JetBrains/phpstorm-stubs#contribution-process

**Comment by hver** [comment]
I have mailed the scan of the signed agreement to jetbrains today.

**Comment by klikh** [comment]
Agreement received. Thank you.

**Comment by scy** [comment]
As far as I can see, you have specified the return type correctly as being `MongoCommandCursor`, but did not include a definition for that class?

**Comment by hver** [comment]
@scy I'll add this definition in a new PR :)

**Pull request merged**
