### PR TITLE
add fastDFS

### PR DESCRIPTION
**Pull request by jingmian**

### CODE REVIEW

**Comment by bzixilu** [comment]
@jingmian  First of all. Thank you for your contribution. 

Secondly, I have 2 suggestions regarding this PR: 
1) Please take a look at failed tests and fix the problems in fastDFS stubs to make the tests green. 
2) Please provide PHPDocs only in English since they can be used further by English-speaking developers

**Comment by jingmian** [comment]
@bzixilu Thank you, I will submit it again after the repair is completed. Can I add an additional Chinese description after I add the English description?

**Comment by andrey-sokolov** [comment]
@jingman Unfortunately for now we work with English descriptions only. We need to provide some additional functionality/workflow to work with multiple languages in a proper way. Still you can try to provide it as a separate extension via Settings> Languages & Frameworks > PHP Runtime > Default stubs path or with https://github.com/artspb/phpstorm-library-plugin.

**Comment by jingmian** [comment]
@andrey-sokolov thanks

**Comment by andrey-sokolov** [comment]
@jingmian Hey, would you, please, give us any estimates on your fixes?

**Pull request closed without merging**
