### PR TITLE
DomNode unimplemented methods have been removed in PHP 8.0

### PR DESCRIPTION
**Pull request by Bellangelo**
Reference: https://www.php.net/manual/en/class.domnode.php

> 8.0.0 | The unimplemented methods DOMNode::compareDocumentPosition(), DOMNode::isEqualNode(), DOMNode::getFeature(), DOMNode::setUserData() and DOMNode::getUserData() have been removed.

### CODE REVIEW

**Comment by LolGleb** [comment]
Thank you for your PR! I have checked all the mentioned methods and it seems that `DOMNode::isEqualNode()` was reintroduced in php 8.3 https://github.com/php/php-src/pull/11690
I believe we shouldn't mark it as removed in this case.

**Comment by Bellangelo** [comment]
> Thank you for your PR! I have checked all the mentioned methods and it seems that `DOMNode::isEqualNode()` was reintroduced in php 8.3 [php/php-src#11690](https://github.com/php/php-src/pull/11690)
> I believe we shouldn't mark it as removed in this case.

Hmm.. interesting. I guess I will have to open a PR in the docs as well :D.

Nevertheless, will something like this work? How do handle such cases?
```php
/**
 * @since 5.6
 * @removed 8.0
 * @since 8.3
*/
public function method(): void;
```

**Comment by LolGleb** [comment]
I wasn't able to find similar cases in the project... I don't think that it's allowed to have more than one `@since` mark in a PHPDoc. I guess the best thing we can do is simply leave this method without `@removed` or `@since` marks.

**Comment by nielsdos** [comment]
compareDocumentPosition is also reintroduced with an actual implementation in PHP 8.4.

**Comment by LolGleb** [comment]
You are right. That means it should be also left without `@removed` mark.

**Comment by Bellangelo** [comment]
@LolGleb @nielsdos I have removed the `@removed` from the `compareDocumentPosition` and `isEqualNode`.

**Pull request merged**
