### PR TITLE
Add newrelic stubs

### PR DESCRIPTION
**Pull request by Mezzle**
via @olekhy

### CODE REVIEW

**Comment by olekhy** [comment]
:+1:

**Comment by Mezzle** [comment]
Apologies :) so used to my pre-commit hooks :)

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by Mezzle** [comment]
Seems #49 beat me to it, even though I'd submitted first... :-1:

**Comment by neuro159** [comment]
Well #49 also been kind to send his CLA in advance. Please do follow contribution rules if you wish to add/fix something.

**Comment by Mezzle** [comment]
Which I'd have done, had the [https://github.com/blog/1184-contributing-guidelines](Contributing Guidelines) shown!

**Pull request closed without merging**
