### PR TITLE
Update Core_c.php

### PR DESCRIPTION
**Pull request by WinterSilence**
key can be string or integer

### CODE REVIEW

**Comment by isfedorov** [comment]
Can't agree https://3v4l.org/PTJBY https://3v4l.org/rcpGo

**Comment by WinterSilence** [comment]
@isfedorov it's must be compatible with `key()`

**Comment by WinterSilence** [comment]
@isfedorov https://www.php.net/manual/ru/language.types.array.php#example-54

> The key can either be an int or a string.

**Comment by WinterSilence** [comment]
@isfedorov that iterator? lol
~~~php
private $array = array(
    true => "firstelement",
    false => "secondelement",
);
~~~

**Comment by WinterSilence** [comment]
@isfedorov I've done it a long time ago, for example before 5.5 key can be object... 

focus on this:
> Additionally the following key casts will occur:
    Strings containing valid decimal ints, unless the number is preceded by a + sign, will be cast to the int type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
    Floats are also cast to ints, which means that the fractional part will be truncated. E.g. the key 8.7 will actually be stored under 8.
    Bools are cast to ints, too, i.e. the key true will actually be stored under 1 and the key false under 0.
    Null will be cast to the empty string, i.e. the key null will actually be stored under "".
    Arrays and objects can not be used as keys. Doing so will result in a warning: Illegal offset type.

**Pull request closed without merging**
