### PR TITLE
PHP 7 related changes: WI-27461 PHP7: add intdiv() function WI-27465 PHP_INT_MIN, Throwable interface, IntlChar, Closure::call

### PR DESCRIPTION
**Pull request by andrey-sokolov**

### CODE REVIEW

**Comment by neuro159** [comment]
Ensuring a clean patch and honouring new @since convention would be great.

**Comment by neuro159** [comment]
Merged manually

**Comment by neuro159** [comment]
Please re-do against CURRENT version with proper @since tags, pay attention to history if unsure.

**Comment by andrey-sokolov** [comment]
added '@since' change

**Comment by andrey-sokolov** [comment]
added new patch

**Pull request merged**
