### PR TITLE
RedisArray->info() does not accept any parameter

### PR DESCRIPTION
**Pull request by CyberLine**

### CODE REVIEW

**Comment by Leneshka-jb** [comment]
Actually `https://redis.io/commands/info` provides way more keys. Also does it actually return string or associative array?

**Comment by bzixilu** [comment]
@CyberLine Hi, any updates regarding the question asked above?

**Comment by CyberLine** [comment]
I have added the missing info values and return types

**Comment by bzixilu** [comment]
Thank you for your contribution, merged!

**Pull request merged**
