### PR TITLE
Stub Ev - http://php.net/manual/en/book.ev.php

### PR DESCRIPTION
**Pull request by zwilias**

### CODE REVIEW

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by neuro159** [comment]
can you please move the stub into its separate folder (==module name)?
we're in the midst of the cleanup to simplify control over modules
(UI allowing per-project switching is also added)

**Comment by zwilias** [comment]
Done.

Do you still need me to submit a CLA?

**Comment by neuro159** [comment]
Nope, we were able to get rid of that.

**Pull request merged**
