### PR TITLE
igbinary support

### PR DESCRIPTION
**Pull request by Denitz**
Support for igbinary extension, see https://github.com/igbinary/igbinary

### CODE REVIEW

**Comment by neuro159** [comment]
can you please move the stub into its separate folder (==module name)?
we're in the midst of the cleanup to simplify control over modules
(UI allowing per-project switching is also added)

**Comment by alexz707** [comment]
any progress on this PR ? Ping @Denitz ;)

**Comment by Denitz** [comment]
@alexz707  Move to `/standard/igbinary/igbinary.php` or `/igbinary/igbinary.php` ? I don't see any other separate folders for non-standard extensions yet.

**Comment by alexz707** [comment]
I'm not a maintainer of this repository but I think it seems legit if you create `/igbinary/igbinary.php`. It's not a standard lib so this is the way to go?! ;)

**Comment by Denitz** [comment]
Ready.

**Pull request merged**
