### PR TITLE
Fixed names of TRUE, FALSE and NULL constants

### PR DESCRIPTION
**Pull request by kukulich**
See https://3v4l.org/A6El3

### CODE REVIEW

**Comment by b1rdex** [comment]
Actually this 3 ones are magic in php. You can use them in any case (e.g. `tRuE` or `nuLL`).
I'm personally 👎 on this change.

**Comment by kukulich** [comment]
@b1rdex Yes, it works because of the third parametr of function `define`. However the right names are uppercased.

**Comment by wbars** [comment]
Thank you for the investigation. 
Although formally you are correct, I agree with @b1rdex at this one - these constants are case-insensitive. 
Also I don't see how this change will improve PhpStorm code analysis.

**Comment by kukulich** [comment]
@wbars This PR (and my others) helps using this repository as composer package, mostly currently in https://github.com/Roave/BetterReflection

BetterReflection is used in https://github.com/humbug/php-scoper
PHP-Scoper is used in https://github.com/humbug/box

And Box is used to creating PHAR for tools like PHPUnit, PHPStan etc.

So it will really help PHP ecosystem :)

**Pull request closed without merging**
