### PR TITLE
Total reorganization of stubs

### PR DESCRIPTION
**Pull request by Dragonrun1**
Basically thought it was time to help make the stubs look like they are being professionally done and not just a random afterthought.

### CODE REVIEW

**Comment by neuro159** [comment]
Behind any appearing to randomness there is a purpose and a direction that this stuff moves to.

While we are grateful for any contribution we strongly suggest coordinating such a reorganisational efforts with us before spending your time on it.

**Comment by Dragonrun1** [comment]
And normally I would have but was offline for a week and had a little time on my hands and a problem with an auto-complete being incorrect finally got to me and I decided I'd see what I could do to fix it and once I did that I just didn't stop ;) As far as direction I did look back through the commit history and didn't really see anything that seemed to show any unified direction to make things better IMHO anyway. Some extensions where using _c for classes while others did not, some used _d for the declares other not and put them before or after the other stuff. Some used _f for the functions but once again not all of them. Basically everyone was doing their own thing and it was just become more of a mess as time was going on from what I could tell. The individual DocBlocks etc have been getting better but the overall consistently was not. Just to be clear about it I wasn't trying to step on anyone's toes but just thought things could be a lot better and had the time to do what needed done IMHO anyway.

If anyone has some ideas how to improve on what I did I'm more than happy to look at making changes the idea was to try not re-inventing the wheel a bunch or only once maybe;) and have something that anyone can look at and understand what's going on in 5 minutes or less. Having work on many open source projects the ones that have consistent structure and code styling etc always do better. I known I find myself helping on project more that have what I was trying to add even when I true hate the styling etc they chose I was more willing to help there than on projects that let everyone just do their own thing and the code became almost impossible read or work with. We all use IMHO the best PHP editor there is which allows us to be more productive and make our code look good with little work there's no reason not to use that for some of it own internal workings as well.

On a separate note I've got several updates pushed to my fork improving on some of the extensions themselves more as well. My intention is to fix up all the 'new' ones like array, string etc now that they are all together so they don't look like 20 people just hack something together but actually had a plan from the start ;) Take a look and let me know what you think.

**Comment by Dragonrun1** [comment]
Okay so looks like not interested in my idea on how to improve things that fine I'll continue to make improvement on my fork and use it and anyone else is welcome to as well :)

**Comment by neuro159** [comment]
Dude, I'm on vacation.

As to changes - your changes do conflict with significant changes that are
coming soon. Extension separation, optional extensions, etc.

Trying to *split* the only sane machine oriented source of this information
accumulated in years due to aesthetics and "I've spent a week offline" is
not exactly what helps php community. Quite a disappointing attitude (

I'll be back in a week and if you eager to actually help with stubs, we can
talk

**Comment by Dragonrun1** [comment]
As I've stated wasn't really trying to step on people's toes on this and I wasn't really happy with how big the change ended up but didn't see any way to do it with smaller changes that fixed what I was seeing. If anyone has some suggestion on a better way to do everything I did that would be more likely to be expected then let me known and I'll look at doing new PRs. One advantage is now that I've done the large changes on my fork it's much easier to make any other changes because everything is more consistent and I can continue to make it more so as I have time or need. I just felt once I looked into it that there was no reason to wait for someone else to do what I saw as very easy fixes. And as always I like to give back on any open source project as well so I did the PR. I'd like to see in the main project get to the same level of consistence etc as well since I'm not really looking to take on another project right now but until then I have my fork.

I've been using my version here and it does seem to solve some issues I've noticed in the past plus PHPStorm seems to be a little more responsive but that could be just diff between coming from the jar vs not etc. It could be my imagination as well since I haven't really done any testing but it is noticeable  to me anyway ;)

Hope you vacation has been good and I do look forward to hear from you neuro159.

**Comment by neuro159** [comment]
The point is that there are multiple goals we pursue and "look like they are being professionally done" is the last of them.

- we changed repo layout for new 2017.1 per-project-extension control feature
- we won't accept renaming/reformatting just for the sake of it - we NEED TO PRESERVE MEANINGFUL HISTORY

For any other changes NOT conflicting with above please create a separate requests.

**Comment by neuro159** [comment]
And, nope, your changes can't improve the performance.

**Comment by Dragonrun1** [comment]
I have to ask what you mean by meaningful history? I didn't really understand that when I read it before either in the markdown file.

I'll look at some of the stuff I've done and see if I can separate from the other changes but much of the de-dupping etc will be hard to do with some larger changes probably.

I didn't figure it was faster but was just me ;) Think it interesting though in the MD file it say something about not wanting all the extensions done at once because they did slow things down. Is that still true or has things improved since that was written and it should be updated?

**Pull request closed without merging**
