### PR TITLE
Remove removed flag

### PR DESCRIPTION
**Pull request by mlazdans**
ibase_* functions has not been REMOVED but rather MOVED to PECL and eventually here: https://github.com/FirebirdSQL/php-firebird.

### CODE REVIEW

**Comment by isfedorov** [comment]
@mlazdans Thank you for the PR! Could you please also update `\StubTests\TestData\Providers\Stubs\PhpCoreStubsProvider::$StubDirectoryMap` and move `interbase` extension from `External` to `PECL` list?

**Comment by mlazdans** [comment]
Done.

**Comment by isfedorov** [comment]
@mlazdans the only problem with PR is code style errors. Could you please run cs fixer with a command `docker-compose -f docker-compose.yml run test_runner composer cs-fix` and commit changed files after that?

**Comment by mlazdans** [comment]
I can not get docker running on my machine and I gave up on it.

Looks like it did not like empty comments.

**Pull request merged**
