### PR TITLE
Templatize ArrayObject’s stub

### PR DESCRIPTION
**Pull request by MatTheCat**
Attempt at [WI-70459](https://youtrack.jetbrains.com/issue/WI-70459).

### CODE REVIEW

**Comment by isfedorov** [comment]
Tests fail due to tag `@param callable(TValue, TValue):int`. We use `"phpdocumentor/reflection-docblock"` to parse PHPDoc tags and phpdocumentor can't parse such custom tag. That's why parsing of such tag should be processed separately. Please see `\StubTests\Model\PHPDocElement::collectTags` and update method so it change `@param callable(TValue, TValue):int` to `@param callable` (like it's done for `int<a,b>` with just replacing it to `preg_replace("/int\<\w+,\s*\w+\>/", "int", $text);`

**Comment by MatTheCat** [comment]
@isfedorov thanks; is https://github.com/JetBrains/phpstorm-stubs/pull/1511/commits/c482b1ee0c2bd717f7a50bbbfb0a8dde15069c60 okay?

**Comment by isfedorov** [comment]
@MatTheCat yes, but unfortunately, it's still not enough. The same trick should be done for other custom type declarations like `ArrayIterator<TKey,TValue>` and `array<Tkey, TValue>`. Could you please update `\StubTests\Model\PHPDocElement::collectTags` accordingly?

**Comment by MatTheCat** [comment]
Hmm I see such types are already present in the codebase, like https://github.com/JetBrains/phpstorm-stubs/blob/ccff41f1a6b40ff4ecfaa4964fa5007fa78f6225/Core/Core_c.php#L798

Are you sure `PHPDocElement` has to be updated here?

**Comment by isfedorov** [comment]
@MatTheCat Oh, you are right. Sorry, I gave you the wrong spot. The problem is with `class-string`. phpdocumentor fails to parse this tag and it should be changed to `string`

**Comment by MatTheCat** [comment]
I see `class-string` is already used as well: https://github.com/JetBrains/phpstorm-stubs/blob/b543df50f5d71e4350b9e09f6758ff08f476d50b/Reflection/ReflectionParameter.php#L284

Now I don’t understand :sweat_smile:

**Comment by isfedorov** [comment]
@MatTheCat well..this is how the `"phpdocumentor/reflection-docblock"` works =\ It can parse simple cases like `class-string<T>`
Screenshot 2023-01-09 at 11 48 54
But can't parse complex cases like `class-string<ArrayIterator<TKey,TValue>>`
Screenshot 2023-01-09 at 11 50 10

**Comment by isfedorov** [comment]
@MatTheCat in the latest changes you missed the change for `callable` that you've done before. It's still required

**Comment by MatTheCat** [comment]
Daaaamn, updated :crossed_fingers:

**Comment by isfedorov** [comment]
Fixed in #1517 1517

**Pull request closed without merging**
