### PR TITLE
Add GitHub templates

### PR DESCRIPTION
**Pull request by SerafimArts**
1) Adding a template will allow new or inexperienced participants to formulate their problem more easily.
2) Having a description of the problem to be solved will allow reviewers to quickly understand what the participant is trying to do with the help of this PR (or issue).
3) Well, in general, these are the rules of good form =)

More about the templates here: https://help.github.com/en/articles/about-issue-and-pull-request-templates

### CODE REVIEW

**Comment by voku** [comment]
We could also add different issue templates e.g. https://github.com/kalessil/phpinspectionsea/tree/master/.github/ISSUE_TEMPLATE/

**Comment by SerafimArts** [comment]
However, this repository does not contain `issues` section, so even my template addition looks rather dubious

**Comment by King2500** [comment]
I don't see an issue tab at this GitHub repository... ?

**Comment by SerafimArts** [comment]
@King2500 issues is an illusion :sparkles:

**Comment by wbars** [comment]
Thank you for bringing attention to the problem. Right now we're in process of composing GitHub templates, which will make contribution process easier for both us and contributors. 

Unfortunately, suggested template are quite general and I don't see how they can improve process of contributing, so I will close this PR. 

Thank you again for pointing this out.

**Pull request closed without merging**
