### PR TITLE
Proposed fix for WI-28837

### PR DESCRIPTION
**Pull request by MartyIX**
https://youtrack.jetbrains.com/issue/WI-28837

I hope this is the correct way to add the missing optional parameters.

### CODE REVIEW

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by MartyIX** [comment]
I haven't. Why can't I simply fill in the form online? I would like to see my patch in PhpStorm but I don't want to print anything. Mostly because those hell machines never work and it takes me too much time to make it work..

**Comment by neuro159** [comment]
Well.. On a Mac I can use Preview app's Signature tool to sign the PDF via touchpad and fill it in and then send it.

**Comment by klikh** [comment]
The CLA was received. Thanks.

**Pull request merged**
