### PR TITLE
Pecl AMQP stubs

### PR DESCRIPTION
**Pull request by boekkooi**
This PR adds stubs for https://pecl.php.net/package/amqp

related to https://youtrack.jetbrains.com/issue/WI-15322

### CODE REVIEW

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by boekkooi** [comment]
@neuro159 Yep did it this morning before sending any PR's

**Comment by neuro159** [comment]
Thanks, we're quite distributed and syncing this stuff takes some time )

**Comment by stof** [comment]
:+1: for including them.

btw, the pecl extension maintains its stubs: https://github.com/pdezwart/php-amqp/tree/master/stubs

It would be great to find a way to update the PHPStorm stubs easily based on the upstream ones

**Comment by mente** [comment]
any updates on merge?

**Comment by boekkooi** [comment]
@neuro159 Any chance of getting this merged any time soon?

**Pull request merged**
