### PR TITLE
Change \AMQPExchange::publish route arg default value

### PR DESCRIPTION
**Pull request by b1rdex**
`AMQPExchange::publish() expects parameter 2 to be string, null given`

### CODE REVIEW

**Comment by wbars** [comment]
I'm not quite sure that `''` will be the better choice for the default value.

Based on the [source code](https://github.com/pdezwart/php-amqp/blob/master/amqp_exchange.c#L442) of method arguments parsing we can see, that for a second parameter we have `s!` directive, which means that [null values are explicitly allowed](https://github.com/php/php-src/blob/ef4b2fc283ddaf9bd692015f1db6dad52171c3ce/README.PARAMETER_PARSING_API#L80).

**Comment by b1rdex** [comment]
> directive, which means that [null values are explicitly allowed](https://github.com/php/php-src/blob/ef4b2fc283ddaf9bd692015f1db6dad52171c3ce/README.PARAMETER_PARSING_API#L80)

If you try to pass route value `null` to `publish` it'll generate error from issue body.
Can't send test example because eval.org has no amqp

**Comment by MaXal** [comment]
I've just tried to run the following code:
```
<?php /** @noinspection PhpUnhandledExceptionInspection */

// Create a connection
$connection = new AMQPConnection(['host'=>'localhost','port'=>5672,'password'=>'guest','login'=>'guest']);
$connection->connect();
//Create and declare channel
$channel = new AMQPChannel($connection);
try {
    //Declare Exchange
    $exchange_name = 'logs';
    $exchange = new AMQPExchange($channel);
    $exchange->setType(AMQP_EX_TYPE_FANOUT);
    $exchange->setName($exchange_name);
    $exchange->declareExchange();
    //Do not declasre the queue name by setting AMQPQueue::setName()
    $queue = new AMQPQueue($channel);
    $queue->setFlags(AMQP_EXCLUSIVE);
    $queue->declareQueue();
    $queue->bind($exchange_name,$queue->getName());
    echo sprintf("Queue Name: %s", $queue->getName()), PHP_EOL;
} catch(Exception $ex) {
    print_r($ex);
}
//Read from stdin
$message = implode(' ',array_slice($argv,1));
if(empty($message))
    $message = "info: Hello World!";
$exchange->publish($message, null); //NOTE I'm passing null here 
echo " [X] Sent {$message}", PHP_EOL;
$connection->disconnect();
```
and it works as expected.

I've used: `docker run --hostname my-rabbit --name some-rabbit -p 5672:5672 rabbitmq:3` to run server and have `amqp    1.9.4   stable`.

**Comment by b1rdex** [comment]
@MaXal please add `declare(strict_types=1);` to your code.

```
vagrant@vagrant-centos65 /vagrant head -n5 amqp.php
<?php

declare(strict_types=1);

// Create a connection
vagrant@vagrant-centos65 /vagrant php amqp.php
Queue Name: amq.gen-DUspfHEF0FtCf4OzKlnAZw
PHP Fatal error:  Uncaught TypeError: AMQPExchange::publish() expects parameter 2 to be string, null given in /vagrant/amqp.php:31
Stack trace:
#0 /vagrant/amqp.php(31): AMQPExchange->publish('info: Hello Wor...', NULL)
#1 {main}
  thrown in /vagrant/amqp.php on line 31
vagrant@vagrant-centos65 /vagrant php -v
PHP 7.3.5 (cli) (built: May  1 2019 10:02:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
vagrant@vagrant-centos65 /vagrant php -i | grep -E '^amqp$' -A2
amqp

Version => 1.9.4
```

**Pull request merged**
