### PR TITLE
update stubs for ext-parallel

### PR DESCRIPTION
**Pull request by Frago9876543210**
I have already described why this is necessary here: https://github.com/JetBrains/phpstorm-stubs/pull/594#issuecomment-519405230

### CODE REVIEW

**Comment by WyriHaximus** [comment]
> 1. Why it should be "is valid PHP 7.0 code" when parallel supports 7.2+?

Just realised I might have misinterpreted this comment: https://github.com/JetBrains/phpstorm-stubs/pull/600#issuecomment-502100847 

> 2. What about anonymous channels?

Good catch, seems to have missed that one when syncing up with 1.1.

> 3. `Events\Event\Type` should not be null because `Event->type` will be just magic number. What can confuse you when you do var_dump of event

See: https://github.com/krakjoe/parallel/issues/37#issuecomment-493502459

But kinda missing your bullet point about changing the code style on all the files, including the ones that didn't changes according to your list...

**Comment by Frago9876543210** [comment]
> Yes, but their values are an implementation detail that you cannot rely on, you can only rely on their name and meaning.

These are automatically generated stubs and until the extension updates them, they are correct. In case of update someone will just regenerate stubs

**Comment by WyriHaximus** [comment]
> > Yes, but their values are an implementation detail that you cannot rely on, you can only rely on their name and meaning.
> 
> These are automatically generated stubs and until the extension updates them, they are correct. In case of update someone will just regenerate stubs

Ah cool didn't realise they where generated. That makes it look less of a dickmove as all files have been changed. Where can we find said generator?

**Comment by Frago9876543210** [comment]
https://github.com/Frago9876543210/extension-stub-generator
phpdoc written manually. Although it’s probably not difficult to automate this if ext have documentation on php.net

**Comment by WyriHaximus** [comment]
Thanks :+1:

**Comment by MaXal** [comment]
Please run `php generate-stub-map` and commit `PhpStormStubsMap` otherwise the tests are failing.

**Comment by Frago9876543210** [comment]
What's wrong?

**Comment by WyriHaximus** [comment]
Looks like a Travis glitch :scream:

**Comment by bzixilu** [comment]
Merged, thank you!

**Pull request merged**
