### PR TITLE
Support for SplType extension

### PR DESCRIPTION
**Pull request by lukaszwit**
http://php.net/manual/en/book.spl-types.php

### CODE REVIEW

**Comment by neuro159** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by lukaszwit** [comment]
Just sent

**Comment by lukaszwit** [comment]
Any problem with this?

**Comment by lukaszwit** [comment]
Dear JetBrains can I help you someway with merging it?

**Comment by aik099** [comment]
@lukaszwit , what tool you're using to create that stub?

**Comment by lukaszwit** [comment]
@aik099 I was using phpstrom (EAP at that time)
SplType was enabled in my php and I wrote test lib: https://github.com/lukaszwit/currency

**Comment by aik099** [comment]
No, I mean how did you generate all that method definition with DocBlocks and such?

**Comment by lukaszwit** [comment]
I've wrote it as a compilation of what docs says and what I've experienced when working with this extension. This is not a trivial extension so generating automatically could be sometimes misleading. However I think it is possible to generate it but I don't think Reflection Api would be enough and possibly the source code of this extension should be parsed to generate proper doc blocks.
If you've got an idea or requirement that it should be automatically generated we can think about it.

**Comment by aik099** [comment]
I've tried to reflect the `svn` extension but got empty DocBlocks and methods without parameters as the result. I guess reflection requires something from extension developer to work properly.

**Pull request merged**
